services:
  # fastapi curator service
  curator-service:
    container_name: curator_service
    build:
      context: ./curator_service/ #build context differs because of .toml location
      dockerfile: Dockerfile
    image: curator-service:latest
    ports:
      - "8000:8000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
    volumes:
      - ./curator_service:/app/curator_service # for dev mount code for hot reloading
    restart: unless-stopped 
    # networks:
    #   - app-network # double check this later

  ui:
    container_name: curator_ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: curator-ui:latest
    ports:
        - "80:80"
    depends_on:
        - curator-service
    environment:
        - CURATOR_API_URL=http://curator-service:8000
    volumes:
        - ./ui:/app
    restart: unless-stopped
      # network: app-network