from enum import Enum, unique


@unique
class Scope(str, Enum):
    # IMAGES
    UGC_IMAGE_UPLOAD = 'ugc-image-upload',
    # SPOTIFY CONNECT 
    USER_READ_PLAYBACK_STATE = '', 
    USER_MODIFY_PLAYBACK_STATE = '',
    USER_READ_CURRENTLY_PLAYING = '',
    # PLAYBACK
    APP_REMOTE_CONTROL = '',
    STREAMING = '',
    # PLAYLISTS
    PLAYLIST_READ_PRIVATE = '', 
    PLAYLIST_READ_COLLABORATIVE = '',
    PLAYLIST_MODIFY_PRIVATE = '', 
    PLAYLIST_MODIFY_PUBLIC = '',
    # FOLLOW
    USER_FOLLOW_MODIFY = '',
    USER_FOLLOW_READ = '',
    # LISTENING HISTORY
    USER_READ_PLAYBACK_POSITION = '',
    USER_TOP_READ = '',
    USER_READ_RECENTLY_PLAYED = '',
    # LIBRARY
    USER_LIBRARY_MODIFY = '',
    USER_LIBRARY_READ = '', 
    # USER
    USER_READ_EMAIL = '',
    USER_READ_PRIVATE = '',
    # OPEN ACCESS
    USER_SOA_LINK = '',
    USER_SOA_UNLINK = '',
    USER_MANAGE_ENTITLEMENTS = '',
    USER_MANAGE_PARTNER = '',
    USER_CREATE_PARTNER = '',